AWSTemplateFormatVersion: '2010-09-09'  
Transform: 'AWS::Serverless-2016-10-31'  
Description: Lambda - Quotes  

# Parameters:
#   BucketNamePhotos:
#     Type: String
#     Default: 'smartalbum.album-test'
#     AllowedPattern: "[A-Za-z0-9-]+"
#   FunctionNameLF1:
#     Type: String
#     Default: Assignment3-LF1-test  # Don't change this
#     AllowedValues: 
#       - Assignment3-LF1-test
#     AllowedPattern: "[A-Za-z0-9-]+"

Resources:  
  developerlambdaquotes:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: Assignment3-LF2-test
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      Description: Lambda - Quotes
      MemorySize: 128
      Timeout: 7
      Layers:
        - !Ref libs
      Role: >-
        arn:aws:iam::434531902054:role/service-role/Assignment3-LF2-role-xyuzzwc3
  libs:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: elasticsearch-lib
      Content:
        S3Bucket: layer.lambda.aws
        S3Key: elasticsearch.zip
      CompatibleRuntimes:
        - python3.8
